/^u/.test(typeof define)&&function(x){var v=this.require=function(q){return x[q]};this.define=function(q,r){x[q]=x[q]||r(v)}}({});
define("minified",function(){function x(a){return a.substr(0,3)}function v(a){return"string"==typeof a}function q(a){return a&&a.nodeType}function r(a){return a}function n(a,c,b){return(null!=a?""+a:"").replace(c,null!=b?b:"")}function z(a){return n(a,/^\s+|\s+$/g)}function y(a,c,b){for(var d in a)a.hasOwnProperty(d)&&c.call(b||a,d,a[d]);return a}function m(a,c,b){if(a)for(var d=0;d<a.length;d++)c.call(b||a,a[d],d);return a}function T(a,c){var b=[],d=k(c)?c:function(a){return c!=a};m(a,function(c,
f){d.call(a,c,f)&&b.push(c)});return b}function w(a,c,b){var d=[];a(c,function(a,f){p(a=b.call(c,a,f))?m(a,function(a){d.push(a)}):null!=a&&d.push(a)});return d}function t(a,c){var b=[];m(a,function(d,e){b.push(c.call(a,d,e))});return b}function A(a,c){var b=c||{},d;for(d in a)b[d]=a[d];return b}function B(a,c,b){if(k(a))return a.apply(b&&c,t(b||c,r))}function U(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function J(a){return n(a,/[\x00-\x1f'"\u2028\u2029]/g,U)}function F(a,c){return a.split(c)}
function K(a,c){function b(a,b){var d=[];e.call(b||a,a,function(a,c){p(a)?m(a,function(a,b){c.call(a,a,b)}):y(a,function(a,b){c.call(b,a,b)})},c||r,function(){B(d.push,d,arguments)},G);return d.join("")}if(C[a])return C[a];var d="with(_.isObject(obj)?obj:{}){"+t(F(a,/{{|}}}?/g),function(a,c){var b,d=z(a),e=n(d,/^{/),d=d==e?"esc(":"";if(c%2)return(b=/^each\b(\s+([\w_]+(\s*,\s*[\w_]+)?)\s*:)?(.*)/.exec(e))?"each("+(z(b[4])?b[4]:"this")+", function("+b[2]+"){":(b=/^if\b(.*)/.exec(e))?"if("+b[1]+"){":
(b=/^else\b\s*(if\b(.*))?/.exec(e))?"}else "+(b[1]?"if("+b[2]+")":"")+"{":(b=/^\/(if)?/.exec(e))?b[1]?"}\n":"});\n":(b=/^(var\s.*)/.exec(e))?b[1]+";":(b=/^#(.*)/.exec(e))?b[1]:(b=/(.*)::\s*(.*)/.exec(e))?"print("+d+'_.formatValue("'+J(b[2])+'",'+(z(b[1])?b[1]:"this")+(d&&")")+"));\n":"print("+d+(z(e)?e:"this")+(d&&")")+");\n";if(a)return'print("'+J(a)+'");\n'}).join("")+"}",e=new Function("obj","each","esc","print","_",d);99<L.push(b)&&delete C[L.shift()];return C[a]=b}function W(a){return n(a,/[<>'"&]/g,
function(a){return"&#"+a.charCodeAt(0)+";"})}function M(a,c){return K(a,W)(c)}function k(a){return"function"==typeof a&&!a.item}function p(a){return a&&null!=a.length&&!v(a)&&!q(a)&&!k(a)&&a!==N}function X(a,c){var b=[],d={},e;l(a,function(a){l(c(a),function(a){d[e=a.Nia=a.Nia||++Y]||(b.push(a),d[e]=!0)})});return b}function O(a,c,b){return D(a,c,b)[0]}function P(a,c,b){a=u(document.createElement(a));return p(c)||!(null==c||c&&"object"==typeof c)?a.add(c):a.set(c).add(b)}function Q(a){return w(l,
a,function(a){if(p(a))return Q(a);q(a)&&(a=a.cloneNode(!0),a.removeAttribute&&a.removeAttribute("id"));return a})}function u(a,c){return new E(D(a,c))}function D(a,c,b){function d(a){return p(a)?w(l,a,d):a}function e(a){return T(w(l,a,d),function(a){for(;a=a.parentNode;)if(a==c[0]||b)return a==c[0]})}return c?1!=(c=D(c)).length?X(c,function(c){return D(a,c,b)}):v(a)?1!=q(c[0])?[]:b?e(c[0].querySelectorAll(a)):c[0].querySelectorAll(a):e(a):v(a)?document.querySelectorAll(a):w(l,a,d)}function l(a,c){p(a)?
m(a,c):null!=a&&c(a,0);return a}function Z(){this.state=null;this.values=[];this.parent=null}function R(){var a=[],c=arguments,b=c.length,d=0,e=0,f=new Z;f.errHandled=function(){e++;f.parent&&f.parent.errHandled()};var g=f.fire=function(b,c){null==f.state&&null!=b&&(f.state=!!b,f.values=p(c)?c:[c],setTimeout(function(){m(a,function(a){a()})},0));return f};m(c,function V(a,c){try{a.then?a.then(function(a){(a&&"object"==typeof a||k(a))&&k(a.then)?V(a,c):(f.values[c]=t(arguments,r),++d==b&&g(!0,2>b?
f.values[c]:f.values))},function(a){f.values[c]=t(arguments,r);g(!1,2>b?f.values[c]:[f.values[c][0],f.values,c])}):a(function(){g(!0,t(arguments,r))},function(){g(!1,t(arguments,r))})}catch(e){g(!1,[e,f.values,c])}});f.stop=function(){m(c,function(a){a.stop&&a.stop()});return f.stop0&&B(f.stop0)};var h=f.then=function(b,c){function d(){try{var a=f.state?b:c;k(a)?function aa(a){try{var b,c=0;if((a&&"object"==typeof a||k(a))&&k(b=a.then)){if(a===g)throw new TypeError;b.call(a,function(a){c++||aa(a)},
function(a){c++||g.fire(!1,[a])});g.stop0=a.stop}else g.fire(!0,[a])}catch(d){if(!c++&&(g.fire(!1,[d]),!e))throw d;}}(B(a,S,f.values)):g.fire(f.state,f.values)}catch(h){if(g.fire(!1,[h]),!e)throw h;}}var g=R();k(c)&&f.errHandled();g.stop0=f.stop;g.parent=f;null!=f.state?setTimeout(d,0):a.push(d);return g};f.always=function(a){return h(a,a)};f.error=function(a){return h(0,a)};return f}function E(a,c){var b=0;if(a)for(var d=0,e=a.length;d<e;d++){var f=a[d];if(c&&p(f))for(var g=0,h=f.length;g<h;g++)this[b++]=
f[g];else this[b++]=f}else this[b++]=c;this.length=b;this._=!0}function G(){return new E(arguments,!0)}var N=window,H={},I={},Y=1,S;t(F("January,February,March,April,May,June,July,August,September,October,November,December",/,/g),x);t(F("Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",/,/g),x);var C={},L=[];A({each:function(a){return function(c,b,d){return a(this,c,b,d)}}(m),f:0,remove:function(){l(this,function(a){a.parentNode.removeChild(a)})},text:function(){return w(l,this,function(a){return a.textContent}).join("")},
select:function(a){return u(a,this)},get:function(a,c){var b=this,d=b[0];if(d){if(v(a)){var e=/^(\W*)(.*)/.exec(n(a,/^%/,"@data-")),f=e[1],d=I[f]?I[f](this,e[2]):"$"==a?b.get("className"):"$$"==a?b.get("@style"):"$$slide"==a?b.get("$height"):"$$fade"==a||"$$show"==a?"hidden"==b.get("$visibility")||"none"==b.get("$display")?0:"$$fade"==a?isNaN(b.get("$opacity",!0))?1:b.get("$opacity",!0):1:"$"==f?N.getComputedStyle(d,null).getPropertyValue(n(e[2],/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):"@"==
f?d.getAttribute(e[2]):d[e[2]];return c?parseFloat(n(d,/^[^\d-]+/)):d}var g={};(p(a)?l:y)(a,function(a){g[a]=b.get(a,c)});return g}},set:function(a,c){var b=this;if(c!==S){var d=/^(\W*)(.*)/.exec(n(n(a,/^\$float$/,"cssFloat"),/^%/,"@data-")),e=d[1];if(H[e])H[e](this,d[2],c);else"$$fade"==a?this.set({$visibility:c?"visible":"hidden",$opacity:c}):"$$slide"==a?b.set({$visibility:c?"visible":"hidden",$overflow:"hidden",$height:/px/.test(c)?c:function(a,b,d){a=u(d);d={$position:"absolute",$visibility:"hidden",
$display:"block",$height:null};b=a.get(d);d=a.set(d).get("clientHeight");a.set(b);return d*c+"px"}}):"$$show"==a?c?b.set({$visibility:c?"visible":"hidden",$display:""}).set({$display:function(a){return"none"==a?"block":a}}):b.set({$display:"none"}):"$$"==a?b.set("@style",c):l(this,function(b,g){var h=k(c)?c(u(b).get(a),g,b):c;"$"==e?d[2]?b.style[d[2]]=h:l(h&&h.split(/\s+/),function(a){var c=n(a,/^[+-]/);/^\+/.test(a)?b.classList.add(c):/^-/.test(a)?b.classList.remove(c):b.classList.toggle(c)}):"$$scrollX"==
a?b.scroll(h,u(b).get("$$scrollY")):"$$scrollY"==a?b.scroll(u(b).get("$$scrollX"),h):"@"==e?null==h?b.removeAttribute(d[2]):b.setAttribute(d[2],h):b[d[2]]=h})}else v(a)||k(a)?b.set("$",a):y(a,function(a,c){b.set(a,c)});return b},add:function(a,c){return this.each(function(b,d){function e(a){p(a)?l(a,e):k(a)?e(a(b,d)):null!=a&&(a=q(a)?a:document.createTextNode(a),f?f.parentNode.insertBefore(a,f.nextSibling):c?c(a,b,b.parentNode):b.appendChild(a),f=a)}var f;e(d&&!k(a)?Q(a):a)})},offset:function(){for(var a=
this[0],c={x:0,y:0};a;)c.x+=a.offsetLeft,c.y+=a.offsetTop,a=a.offsetParent;return c},g:0,ht:function(a,c){var b;if(2<arguments.length){b=arguments;var d=[];if(b)for(var e=b.length,f=Math.min(b.length,1);f<e;f++)d.push(b[f]);b=d;d=void 0;for(e=0;e<b.length;e++)d=A(b[e],d);b=d}else b=c;return this.set("innerHTML",k(a)?a(b):/{{/.test(a)?M(a,b):/^#\S+$/.test(a)?M(O(a).text,b):a)}},E.prototype);A({request:function(a,c,b,d){d=d||{};var e,f=0,g=R(),h=b&&b.constructor==d.constructor;try{g.xhr=e=new XMLHttpRequest,
g.stop=function(){e.abort()},h&&(b=w(y,b,function(a,b){return w(l,b,function(b){return encodeURIComponent(a)+(null!=b?"="+encodeURIComponent(b):"")})}).join("&")),null==b||/post/i.test(a)||(c+="?"+b,b=null),e.open(a,c,!0,d.user,d.pass),h&&/post/i.test(a)&&e.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),y(d.headers,function(a,b){e.setRequestHeader(a,b)}),y(d.xhr,function(a,b){e[a]=b}),e.onreadystatechange=function(){4!=e.readyState||f++||(200<=e.status&&300>e.status?g.fire(!0,
[e.responseText,e]):g.fire(!1,[e.status,e.responseText,e]))},e.send(b)}catch(k){f||g.fire(!1,[0,null,null!=k?""+k:""])}return g},toJSON:JSON.stringify,parseJSON:JSON.parse,b:null,h:0},u);A({each:m,toObject:function(a,c){var b={};m(a,function(a){b[a]=c});return b},template:K,a:0,c:0},G);return{HTML:function(){var a=P("div");return G(B(a.ht,a,arguments)[0].childNodes)},$:u,$$:O,EE:P,M:E,getter:I,setter:H}});
